name: trener_jezykowy
description: Trener Językowy — nauka słówek (Anielka)
publish_to: "none"
version: 0.0.2+4

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.8.1
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/baza.json
    - assets/data/portal.json
    - assets/images/kitten_book.png
    - assets/audio/
